name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Login to Github Container Registory
      uses: docker/login-action@v1
      with:
        registory: ghcr.io
        username: ${{ github.registory_owner }}
        password: ${{ secrets.CR_PAT }}
    
    - name: Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tag: docheio/code-server:latest
